auto_ping:
  ping_interval:
    secs: 900
    nanos: 0
  filter:
    node_name_regex: ""
  retry_failed:
    count: 3
    min_interval:
      secs: 10
      nanos: 10
    max_interval:
      secs: 10
      nanos: 10
subscpt:
  path: v2ray-subscription.txt
  url: https://www.jinkela.site/link/ukWr5K49YjHIQGdL?sub=3
  update_interval:
    secs: 43200
    nanos: 0
  retry_failed:
    count: 3
    min_interval:
      secs: 2
      nanos: 0
    max_interval:
      secs: 60
      nanos: 0
switch:
  check_url: https://www.google.com/gen_204
  check_timeout:
    secs: 2
    nanos: 0
  filter: 
    lb_nodes_size: 3
    name_regex: "香港"
  retry:
    count: 7
    min_interval:
      secs: 0
      nanos: 100000000
    max_interval:
      secs: 40
      nanos: 0
  ssh:
    username: root
    host: openwrt
    config_path: "/var/etc/ssrplus/tcp-only-ssr-retcp.json"
v2:
  config_path: /var/etc/ssrplus/tcp-only-ssr-retcp.json
  # concurr_num: 20

ping:
  count: 3
  ping_url: https://www.google.com/gen_204
  timeout:
    secs: 1
    nanos: 500000
