auto_ping:
  ping_interval:
    secs: 10
    nanos: 10
  retry_failed:
    count: 3
    min_interval:
      secs: 10
      nanos: 10
    max_interval:
      secs: 10
      nanos: 10
subscpt:
  path: v2ray-subscription.txt
  url: https://www.jinkela.site/link/ukWr5K49YjHIQGdL?sub=3
  update_interval:
    secs: 43200
    nanos: 0
  retry_failed:
    count: 3
    min_interval:
      secs: 2
      nanos: 0
    max_interval:
      secs: 60
      nanos: 0
switch:
  check_url: https://www.google.com/gen_204
  check_timeout:
    secs: 2
    nanos: 0
  lb_nodes_size: 3
  retry:
    count: 3
    min_interval:
      secs: 2
      nanos: 0
    max_interval:
      secs: 30
      nanos: 0

v2:
  config_path: /var/etc/ssrplus/tcp-only-ssr-retcp.json
  concurr_num: 2

ping:
  count: 3
  ping_url: https://www.google.com/gen_204
  timeout:
    secs: 2
    nanos: 0
filter:
  node_name_regex: "→香港01"
